pivnet_token: (( vault "secret/pcfops/tmpsandbox/pivnet-token:value" ))
git_private_key: (( vault "secret/pcfops/tmpsandbox/ssh/github:ssh-private-key" ))

opsman_major_minor_version: ^1\.10\..*$
ert_major_minor_version: ^1\.10\..*$

# Errands to disable prior to deploying ERT
# Valid values:
#   all
#   none
#   "" (empty string)
#   Any combination of the following, separated by comma:
#     smoke-tests
#     push-apps-manager
#     notifications
#     notifications-ui
#     push-pivotal-account
#     autoscaling
#     autoscaling-register-broker
#     nfsbrokerpush
ert_errands_to_disable: none

# RDS Master Credentials
db_master_username: admin
db_master_password: (( vault "secret/pcfops/tmpsandbox/rds-db-password:value" ))

# ERT Database Credentials
db_app_usage_service_username: admin
db_app_usage_service_password: (( vault "secret/pcfops/tmpsandbox/rds-db-password:value" ))
db_autoscale_username: admin
db_autoscale_password: (( vault "secret/pcfops/tmpsandbox/rds-db-password:value" ))
db_diego_username: admin
db_diego_password: (( vault "secret/pcfops/tmpsandbox/rds-db-password:value" ))
db_notifications_username: admin
db_notifications_password: (( vault "secret/pcfops/tmpsandbox/rds-db-password:value" ))
db_routing_username: admin
db_routing_password: (( vault "secret/pcfops/tmpsandbox/rds-db-password:value" ))
db_uaa_username: admin
db_uaa_password: (( vault "secret/pcfops/tmpsandbox/rds-db-password:value" ))
db_ccdb_username: admin
db_ccdb_password: (( vault "secret/pcfops/tmpsandbox/rds-db-password:value" ))
db_accountdb_username: admin
db_accountdb_password: (( vault "secret/pcfops/tmpsandbox/rds-db-password:value" ))
db_networkpolicyserverdb_username: admin
db_networkpolicyserverdb_password: (( vault "secret/pcfops/tmpsandbox/rds-db-password:value" ))
db_nfsvolumedb_username: admin
db_nfsvolumedb_password: (( vault "secret/pcfops/tmpsandbox/rds-db-password:value" ))
db_silk_username: admin
db_silk_password: (( vault "secret/pcfops/tmpsandbox/rds-db-password:value" ))
db_locket_username: admin
db_locket_password: (( vault "secret/pcfops/tmpsandbox/rds-db-password:value" ))

terraform_prefix: PcfDojoSB-auto

director_certificates:

TF_VAR_aws_access_key: (( vault "secret/pcfops/tmpsandbox/aws/keys:access_key" ))
TF_VAR_aws_secret_key: (( vault "secret/pcfops/tmpsandbox/aws/keys:secret_key" ))
TF_VAR_aws_key_name: pcf-dojo-bastion
TF_VAR_aws_cert_arn: arn:aws:acm:us-east-1:996608571400:certificate/569b870b-973d-4d41-b320-18449ca86e17
TF_VAR_amis_nat: 
TF_VAR_aws_region: us-east-1
TF_VAR_az1: us-east-1c
TF_VAR_az2: us-east-1d
TF_VAR_az3: us-east-1e

S3_ENDPOINT: https://s3.amazonaws.com
S3_OUTPUT_BUCKET: pcf-dojo-sb-auto-terraform
ERT_DOMAIN: cf.us-east-1.arity-sandbox.com
OPSMAN_USER: admin
OPSMAN_PASSWORD: welcome1
OPSMAN_URI: opsman.cf.us-east-1.arity-sandbox.com
PEM: (( vault "secret/pcfops/tmpsandbox/ssh:bastion-private-key" )) 
ERT_SSL_CERT:
ERT_SSL_KEY:

# if the `opsman_allow` cidr ranges are left blank then there will not be any
# external ingress to ops manager defined in the security group
# ingress from the local network will remain allowed for all protos
opsman_allow_ssh_cidr_ranges:
opsman_allow_https_cidr_ranges: 

mysql_monitor_recipient_email: nobody@aridy.com # Email address for sending mysql monitor notifications
mysql_backups: disable   # Whether to enable MySQL backups. (disable|s3|scp)

#SCP backup config params (leave empty values if you're not using scp
mysql_backups_scp_server:
mysql_backups_scp_port:
mysql_backups_scp_user:
mysql_backups_scp_key:
mysql_backups_scp_destination:
mysql_backups_scp_cron_schedule:

#S3 backup config params (leave empty values if you're not using s3)
mysql_backups_s3_endpoint_url:
mysql_backups_s3_bucket_name:
mysql_backups_s3_bucket_path:
mysql_backups_s3_access_key_id:
mysql_backups_s3_secret_access_key:
mysql_backups_s3_cron_schedule:

# VPC Info
TF_VAR_aws_vpc_PcfVpc: vpc-9aa325e3

#SUBNETS
TF_VAR_vpc_cidr: 172.27.88.0/21
TF_VAR_public_subnet_cidr_az1: 172.27.95.176/28
TF_VAR_PcfVpcPublicSubnet_az1: subnet-11473a59
TF_VAR_public_subnet_cidr_az2: 172.27.95.192/28
TF_VAR_PcfVpcPublicSubnet_az2: subnet-440db01e 
TF_VAR_public_subnet_cidr_az3: 172.27.95.208/28
TF_VAR_PcfVpcPublicSubnet_az3: subnet-45102c79
TF_VAR_ert_subnet_cidr_az1: 172.27.88.0/25
TF_VAR_PcfVpcErtSubnet_az1: subnet-08bdc040
ert_subnet_reserved_ranges_z1: 172.27.88.1 - 172.27.88.14
TF_VAR_ert_subnet_cidr_az2: 172.27.89.0/25
TF_VAR_PcfVpcErtSubnet_az2: subnet-9917aac3
ert_subnet_reserved_ranges_z2: 172.27.89.1 - 172.27.89.14
TF_VAR_ert_subnet_cidr_az3: 172.27.90.0/25
TF_VAR_PcfVpcErtSubnet_az3: subnet-2a0d3116
ert_subnet_reserved_ranges_z3: 172.27.90.1 - 172.27.90.14
TF_VAR_services_subnet_cidr_az1: 172.27.94.0/26
TF_VAR_PcfVpcServicesSubnet_az1: subnet-80413cc8
services_subnet_reserved_ranges_z1: 172.27.94.1 - 172.27.94.6
TF_VAR_services_subnet_cidr_az2: 172.27.94.64/26
TF_VAR_PcfVpcServicesSubnet_az2: subnet-2910ad73
services_subnet_reserved_ranges_z2: 172.27.94.65 - 172.27.94.71
TF_VAR_services_subnet_cidr_az3: 172.27.94.128/26
TF_VAR_PcfVpcServicesSubnet_az3: subnet-ff172bc3
services_subnet_reserved_ranges_z3: 172.27.94.129 - 172.27.94.135
TF_VAR_infra_subnet_cidr_az1: 172.27.88.0/25
TF_VAR_PcfVpcInfraSubnet_az1: subnet-08bdc040
infra_subnet_reserved_ranges_z1: 172.27.88.1 - 172.27.88.6, 172.27.88.15 - 172.27.88.128
TF_VAR_rds_subnet_cidr_az1: 172.27.94.192/27
TF_VAR_PcfVpcRdsSubnet_az1: subnet-efb8c5a7
TF_VAR_rds_subnet_cidr_az2: 172.27.94.224/27
TF_VAR_PcfVpcRdsSubnet_az2: subnet-050cb15f
TF_VAR_rds_subnet_cidr_az3: 172.27.95.0/27
TF_VAR_PcfVpcRdsSubnet_az3: subnet-9e162aa2
TF_VAR_access_subnet_cidr_az1: 172.27.95.128/28
TF_VAR_PcfVpcAccessSubnet_az1: subnet-a64538ee
TF_VAR_opsman_ip_az1: 172.27.95.135
TF_VAR_nat_ip_az1: 172.27.95.181
TF_VAR_nat_ip_az2: 172.27.95.198
TF_VAR_nat_ip_az3: 172.27.95.212
